<?xml version="1.0" encoding="UTF-8" ?><?xml-stylesheet type="text/xsl" href="testharness.xsl"?><testharness><message><timestamp>2021-01-11 16:04:36.441254</timestamp><level>error</level><value>Traceback (most recent call last):
  File "C:\TCPython\TC_testharness\utility.py", line 96, in do_testharness
    t()
  File "TC_transtest_all_autoselect_EMV.py", line 1907, in processTransaction
    result = processEMV(tid)
  File "TC_transtest_all_autoselect_EMV.py", line 1596, in processEMV
    continue_tpl = sendFirstGenAC(tlv, tid)
  File "TC_transtest_all_autoselect_EMV.py", line 1196, in sendFirstGenAC
    TC_TCLink.saveEMVASCIITag((APPLICATION_LABEL))
  File "C:\TCPython\TC_TCLink.py", line 409, in saveEMVASCIITag
    EMV_TAGS[EMV_TAG_ASCII_MAP[tag[0]]] = tag[1].decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 0: invalid continuation byte
 </value></message></testharness>